In [2]:
#Importing Libs and Loading Data
import numpy as np
import pandas as pd

In [3]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')

In [4]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0     False     False     False      True            7                1   
1     False     False     False     False            7                1   
2     False     False     False      True            7                2   
3      True     False     False     False            7                3   
4     False     False     False      True            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30        NaN         2     1                          4  
1               31        NaN         1     0                          0  
2               31        NaN         0     0                          2  
3               24        NaN         2     0                          4  
4               30        NaN         2     1                          2

### Creating the Targets

In [6]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [7]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours']>3,1,0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [8]:
data_preprocessed['Excessive Targets'] = targets

In [9]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0     False     False     False      True            7                1   
1     False     False     False     False            7                1   
2     False     False     False      True            7                2   
3      True     False     False     False            7                3   
4     False     False     False      True            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30        NaN         2     1                          4   
1               31        NaN         1     0                          0   
2               31        NaN         0     0                          2   
3               24        NaN         2     0                          4   
4               30        NaN         2     1                          2   

   Excessive Targets  
0                  1  
1                  0  
2                  0  
3                  1  
4                  0

### Comment on Targets

In [11]:
targets.sum()/targets.shape[0]   #So around 46% of targets are 1 and 55% are 0

0.45571428571428574

In [12]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Daily Work Load Average',
                                           'Distance to Work','Day of the Week'],axis=1)

In [13]:
data_with_targets is data_preprocessed

False

## Selecting Inputs

In [15]:
data_with_targets.shape

(700, 12)

In [16]:
data_with_targets.iloc[:,:14]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0       False     False     False      True            7   
1       False     False     False     False            7   
2       False     False     False      True            7   
3        True     False     False     False            7   
4       False     False     False      True            7   
..        ...       ...       ...       ...          ...   
695      True     False     False     False            5   
696      True     False     False     False            5   
697      True     False     False     False            5   
698     False     False     False      True            5   
699     False     False     False      True            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                       289   33               30        NaN         2     1   
1                       118   50               31        NaN         1     0   
2                       179   38               31        NaN         0     0   
3                       279   39               24        NaN         2     0   
4                       289   33               30        NaN         2     1   
..                      ...  ...              ...        ...       ...   ...   
695                     179   40               22        0.0         2     0   
696                     225   28               24        NaN         1     2   
697                     330   28               25        0.0         0     0   
698                     235   32               25        0.0         0     0   
699                     291   40               25        NaN         1     1   

     Excessive Targets  
0                    1  
1                    0  
2                    0  
3                    1  
4                    0  
..                 ...  
695                  1  
696                  0  
697                  1  
698                  0  
699                  0  

[700 rows x 12 columns]

In [17]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

## Standardizing The Data

In [19]:
# standardize the inputs

# standardization is one of the most common preprocessing tools
# since data of different magnitude (scale) can be biased towards high values,
# we want all inputs to be of similar magnitude
# this is a peculiarity of machine learning in general - most (but not all) algorithms do badly with unscaled data

# a very useful module we can use is StandardScaler 
# it has much more capabilities than the straightforward 'preprocessing' method
from sklearn.preprocessing import StandardScaler


# we will create a variable that will contain the scaling information for this particular dataset
# here's the full documentation: http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html

# define scaler as an object
absenteeism_scaler = StandardScaler()

In [20]:
absenteeism_scaler.fit(unscaled_inputs)

StandardScaler()

In [21]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs )

In [22]:
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ...,         nan,
         0.88046927,  0.26848661],
       [-0.57735027, -0.09298136, -0.31448545, ...,         nan,
        -0.01928035, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ...,         nan,
        -0.91902997, -0.58968976],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ...,  0.        ,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ...,  0.        ,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ...,         nan,
        -0.01928035,  0.26848661]])

In [23]:
scaled_inputs.shape

(700, 11)

### Splitting the Data Into Train and Test 

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
train_test_split(scaled_inputs, targets)

[array([[-0.57735027, -0.09298136, -0.31448545, ...,         nan,
         -0.01928035,  2.8430157 ],
        [-0.57735027, -0.09298136, -0.31448545, ...,         nan,
          0.88046927,  0.26848661],
        [-0.57735027, -0.09298136, -0.31448545, ...,         nan,
          0.88046927,  0.26848661],
        ...,
        [-0.57735027, -0.09298136, -0.31448545, ...,         nan,
         -0.01928035,  1.12666297],
        [ 1.73205081, -0.09298136, -0.31448545, ...,         nan,
         -0.01928035,  1.12666297],
        [-0.57735027, -0.09298136, -0.31448545, ...,         nan,
         -0.01928035,  2.8430157 ]]),
 array([[-0.57735027, -0.09298136, -0.31448545, ...,         nan,
          0.88046927,  0.26848661],
        [-0.57735027, -0.09298136, -0.31448545, ...,         nan,
         -0.01928035,  1.12666297],
        [-0.57735027, -0.09298136, -0.31448545, ...,         nan,
         -0.01928035,  2.8430157 ],
        ...,
        [-0.57735027, -0.09298136, -0.31448545, ...,  

In [27]:
#Train size 0.8 means 80-20 split and random state is for shuffling
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, 
                                                    train_size = 0.8, random_state = 20)

In [28]:
print(x_train.shape, y_train.shape)

(560, 11) (560,)


In [29]:
print(x_test.shape,y_test.shape)

(140, 11) (140,)


## Logistic Regression with Sklearn

In [31]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn import metrics

#### Training the model

In [33]:
# We got input error while processing x_train in log red
# reg = LogisticRegression()
reg = HistGradientBoostingClassifier()

In [34]:
reg.fit(x_train,y_train)

HistGradientBoostingClassifier()

In [35]:
reg.score(x_train,y_train)

0.8892857142857142

#### Manually checking the Accuracy

In [37]:
model_outputs = reg.predict(x_train)

In [38]:
model_outputs

array([0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,

In [39]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [40]:
model_outputs == y_train

array([ True,  True,  True, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False, False,  True,  True,  True,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True, False, False,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,

In [41]:
np.sum((model_outputs==y_train))   #These are the number of trues

498

In [42]:
model_outputs.shape[0]

560

In [43]:
np.sum((model_outputs==y_train)/model_outputs.shape[0])   
#The accuracy is same as we calculated before

0.8892857142857143

### Testing the Model

In [45]:
reg.score(x_test,y_test)

0.7285714285714285

In [81]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.91933388, 0.08066612],
       [0.70985229, 0.29014771],
       [0.64867109, 0.35132891],
       [0.75516663, 0.24483337],
       [0.00120502, 0.99879498],
       [0.5324208 , 0.4675792 ],
       [0.03572301, 0.96427699],
       [0.04477445, 0.95522555],
       [0.88886239, 0.11113761],
       [0.58638825, 0.41361175],
       [0.63607842, 0.36392158],
       [0.1672167 , 0.8327833 ],
       [0.01614389, 0.98385611],
       [0.24785788, 0.75214212],
       [0.27431732, 0.72568268],
       [0.23912688, 0.76087312],
       [0.1180293 , 0.8819707 ],
       [0.19547207, 0.80452793],
       [0.35271662, 0.64728338],
       [0.01062842, 0.98937158],
       [0.89889846, 0.10110154],
       [0.75516663, 0.24483337],
       [0.0966703 , 0.9033297 ],
       [0.0966703 , 0.9033297 ],
       [0.08915274, 0.91084726],
       [0.4895155 , 0.5104845 ],
       [0.55509437, 0.44490563],
       [0.84026748, 0.15973252],
       [0.27019867, 0.72980133],
       [0.75516663, 0.24483337],
       [0.

In [83]:
predicted_proba.shape

(140, 2)

In [85]:
predicted_proba[:,1]

array([0.08066612, 0.29014771, 0.35132891, 0.24483337, 0.99879498,
       0.4675792 , 0.96427699, 0.95522555, 0.11113761, 0.41361175,
       0.36392158, 0.8327833 , 0.98385611, 0.75214212, 0.72568268,
       0.76087312, 0.8819707 , 0.80452793, 0.64728338, 0.98937158,
       0.10110154, 0.24483337, 0.9033297 , 0.9033297 , 0.91084726,
       0.5104845 , 0.44490563, 0.15973252, 0.72980133, 0.24483337,
       0.11061934, 0.59821703, 0.53631866, 0.44466747, 0.24483337,
       0.28271413, 0.06102324, 0.95797183, 0.24258085, 0.91804923,
       0.0187278 , 0.10710125, 0.09447167, 0.5302718 , 0.34155018,
       0.57710141, 0.98247065, 0.08066612, 0.24088023, 0.03218416,
       0.55341362, 0.08518573, 0.4675792 , 0.32992476, 0.94138993,
       0.319895  , 0.96889594, 0.33348873, 0.11224797, 0.03442757,
       0.22761792, 0.84827434, 0.15017795, 0.81311817, 0.70336788,
       0.24491091, 0.06980287, 0.06102324, 0.952391  , 0.89813648,
       0.06102324, 0.06223161, 0.9106932 , 0.06157741, 0.58592

## Saving the Model Now

In [90]:
import pickle

In [92]:
with open('model','wb') as file:
    pickle.dump(reg, file)

In [94]:
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler, file)